import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/widgets/app-sidebar";
import NextAuthProvider from "@/components/wrappers/SessionWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* the auth provider to grant access to session variable through the page*/}
        <NextAuthProvider>
          {/* grant access to the side bar in all states and pages */}
          <SidebarProvider>
            {/* obviously the actual side bar  */}
        <AppSidebar /> 
            <main className="w-full h-full">
              {/* side bar trigger button */}
          <SidebarTrigger />
          {children}
          </main>
        </SidebarProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
